name: "release-winget"
on:
  release:
    types: [released]
  push:
    branches:
      - ldennington/add-release-winget

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - id: update-winget
      name: Update winget repository
      uses: mjcheetham/update-winget@v1.1
      with:
        id: Microsoft.Git
        token: ${{ secrets.WINGET_TOKEN }}   
        releaseAsset: Git-\[0-9.vfs]*\-64-bit.exe
        repo: ldennington/winget-playground
        manifestText: |
          PackageIdentifier: {{id}}
          PackageVersion: {{version}}
          PackageName: Microsoft Git
          Publisher: Microsoft Corporation
          Moniker: microsoft-git
          PackageUrl: https://aka.ms/ms-git
          Tags: "microsoft/git"
          License: Copyright (C) Microsoft Corporation
          ShortDescription: Git distribution to support monorepo scenarios. 
                            Note: This is not Git for Windows - unless you are working in a monorepo and require
                            specific Git modifications, please run `winget install git` to start using Git for Windows.
          Installers:
          - Arch: x64
            Url: {{url}}
            InstallerType: Inno
            Sha256: {{sha256}}
          PackageLocale: en-US
          ManifestType: singleton
          ManifestVersion: 1.0.0
        alwaysUsePullRequest: true
        releaseRepo: 'microsoft/git'
        releaseTag: 'v2.31.1.vfs.0.0'